In [1]:
import torch

In [54]:
tensor = torch.rand(2,2,2,2)
tensor

tensor([[[[0.8075, 0.8219],
          [0.8193, 0.6383]],

         [[0.4155, 0.0513],
          [0.0983, 0.6230]]],


        [[[0.5766, 0.0856],
          [0.5495, 0.8380]],

         [[0.0859, 0.8789],
          [0.7645, 0.2655]]]])

In [2]:
randint = torch.randint(-100,100,(2,6))
randint

tensor([[ 92, -85,  50,  53,  59, -11],
        [ -1,  16,  35,  51, -91, -88]])

In [4]:
tensors = torch.tensor([[1,12,12],
                       [34,22,11],
                       [1,2,3],
                       [4,5,6]])
tensors

tensor([[ 1, 12, 12],
        [34, 22, 11],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [5]:
zeros = torch.zeros(2,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
linspace = torch.linspace(0,10,steps=20)
linspace

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [11]:
eye = torch.eye(4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Now using CUDA 

In [14]:
import time
import numpy as np

In [13]:
device = 'cuda' if torch.cuda.is_available() else 'device'
device

'cuda'

In [27]:
start_time = time.time()
tensors = torch.linspace(-100,100,steps=1000)

end_time = time.time()
final = start_time - end_time
print(f"{final:.100f}")

0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000


# Numpy in CPU vs Torch in CUDA

In [36]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
start_time = time.time()
torch_rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time-start_time
print(f"torch time = {elapsed_time:.5f}")


np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()
np_rand = np.multiply(np_rand1 ,np_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"numpy time =  { elapsed_time:.5f}")

torch time = 0.00199
numpy time =  0.24020


## Torch Function

### 1.Multinomial Probabilities

In [43]:

probabilities = torch.tensor([0.1,0.9])
# 0.1 means 10% and 0.9 means 90%
data = torch.multinomial(probabilities,num_samples=10,replacement=True)
print(data)

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


### 2.Concate two tensor into One, torch.cat()

In [47]:
tensor = torch.tensor([1,2,3,4,5])
out = torch.cat((tensor,torch.tensor([0,3])),dim=0)
out

tensor([1, 2, 3, 4, 5, 0, 3])

### 3.Torch triangle lower shortform torch.tril()

In [57]:
tri = torch.tril(torch.ones(4,4))
tri

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

### 4.Torch triangle higher shortform torch.triu()

In [58]:
triu = torch.triu(torch.ones(4,4))
triu

tensor([[1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.]])

### 5.Torch Mask Fill

In [73]:
inf_value = float('-inf')
mask = torch.tril(torch.ones(5, 5)) == 0
out = torch.ones(5,5).masked_fill(mask, inf_value)
out

tensor([[1., -inf, -inf, -inf, -inf],
        [1., 1., -inf, -inf, -inf],
        [1., 1., 1., -inf, -inf],
        [1., 1., 1., 1., -inf],
        [1., 1., 1., 1., 1.]])

### 6.torch.exp()

In [74]:
torch.exp(out)

tensor([[2.7183, 0.0000, 0.0000, 0.0000, 0.0000],
        [2.7183, 2.7183, 0.0000, 0.0000, 0.0000],
        [2.7183, 2.7183, 2.7183, 0.0000, 0.0000],
        [2.7183, 2.7183, 2.7183, 2.7183, 0.0000],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183]])

### 7.torch.transpose()

In [77]:
zeros = torch.zeros(4,5,2)
transposed = zeros.transpose(0,2) 
# swapped the index 0 with index 2 in zeros shaped 
transposed.shape

torch.Size([2, 5, 4])

### 8.torch.stack()

In [88]:
tensor1 = torch.randint(1,9,(4,))
tensor2 = torch.randint(1,9,(4,))
tensor3 = torch.randint(1,9,(4,))

stack = torch.stack([tensor1,tensor2,tensor3])
stack

tensor([[1, 2, 6, 7],
        [7, 5, 6, 1],
        [5, 5, 7, 6]])

## Simple Linear Neural Network|

In [92]:
import torch.nn as nn
sample = torch.tensor([12,13,120, 9],dtype=torch.float32)
linear = nn.Linear(4,4,bias=False)
linear(sample)

tensor([ 48.3907, -18.2303, -17.3602,  37.9678], grad_fn=<SqueezeBackward4>)

## 10.Softmax function

In [94]:
import torch.nn.functional as F
tensor = torch.tensor([1,5,8,4],dtype=torch.float32)
softmax = F.softmax(tensor,dim=0)
softmax

tensor([8.5301e-04, 4.6573e-02, 9.3544e-01, 1.7133e-02])