In [1]:
import torch

In [3]:
randint = torch.randint(-100,100,(2,6))
randint

tensor([[-53, -88,  40, -87,  39, -45],
        [-76, -74,  51,  64, -52,  28]])

In [5]:
tensors = torch.tensor([[1,12,12],
                       [34,22,11],
                       [1,2,3],
                       [4,5,6]])
tensors

tensor([[ 1, 12, 12],
        [34, 22, 11],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [6]:
zeros = torch.zeros(2,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])